services:
  postgresql:
    build:
      context: docker
    environment:
      - POSTGRES_PASSWORD
    networks:
      - postgresql
      - traefik
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./backups:/var/backups

networks:
  postgresql:
    external: false
  traefik:
    external: true

volumes:
  postgresql:
