#!/bin/bash

# Halt on error
set -e

USER=$1

if [ -z "$USER" ]
then
    echo "The user name is missing. Try again:"
    echo "> set-admin <user>"
    exit 1
fi

psql -q -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
	ALTER USER $USER CREATEDB;
EOSQL

echo "The user $USER can now create databases." \
 | grep --color "^\|$USER\|$PASSWORD"
